<?
$aMenuLinks = Array(
    Array(
        "Классическая абдоминопластика",
        "/uslugi/telo/klassicheskaya-abdominoplastika/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Миниабдоминопластика",
        "/uslugi/telo/miniabdominoplastika/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Брахиопластика",
        "/uslugi/telo/brakhioplastika/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Лабиопластика",
        "/uslugi/telo/intimnaya-plastika-labioplastika/",
        Array(),
        Array(),
        ""
    )
);
?>