<?
$GLOBALS['APPLICATION']->setTitle($arResult['IPROPERTY_VALUES']['SECTION_META_TITLE']);
$GLOBALS['APPLICATION']->SetPageProperty('title', $arResult['IPROPERTY_VALUES']['SECTION_META_TITLE']);
$GLOBALS['APPLICATION']->SetPageProperty('h1', $arResult['IPROPERTY_VALUES']['SECTION_PAGE_TITLE']);
$GLOBALS['APPLICATION']->SetPageProperty('description', $arResult['IPROPERTY_VALUES']['SECTION_META_DESCRIPTION']);
$GLOBALS['APPLICATION']->SetPageProperty('keywords', $arResult['IPROPERTY_VALUES']['SECTION_META_KEYWORDS']);